### ISSUE TITLE
Right and left click throw error

### ISSUE THREAD

**Issue by NoFear4me** [cr4ckp0t/ElvUI_Professions#7]
2x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_Professions' tried to call the protected function 'CastSpellByName()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "@ElvUI_Professions/ElvUI_Professions.lua"]:85: in function `onClick'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:436: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:434>

This happens on either right or left click. Everything else works as advertised.

**Comment by cr4ckp0t** [comment]
This doesn't provide enough information to properly diagnose the potential issue. I would need to know what your primary professions are, were you in combat, etc.?

**Comment by NoFear4me** [comment]
Sorry. Out of combat. My primary is alchemy and my secondary is engineering. The cooking and archaeology work fine. I'm not crazy, my reality is just different than yours.On Feb 23, 2023, at 13:08, Adam Koch ***@***.***> wrote:﻿
This doesn't provide enough information to properly diagnose the potential issue. I would need to know what your primary professions are, were you in combat, etc.?
